Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"


  config.ssh.insert_key = false


  config.vm.define :database do |cfg|
        cfg.vm.network :private_network, ip: "192.155.5.9"
        cfg.vm.provider :virtualbox do |v|
            v.name = "database"
        cfg.vm.provision :shell, :path => "databaseConfig.sh"
        end
    end

  config.vm.define :appvm do |cfg|
        cfg.vm.network "forwarded_port", guest: 8080, host: 8080
        cfg.vm.network :private_network, ip: "192.155.5.10"
        cfg.vm.provider :virtualbox do |v|
            v.name = "appvm"
        cfg.vm.provision :shell, :path => "appConfig.sh"
        end
    end

  config.vm.define :haproxy do |cfg|
        cfg.vm.network :private_network, ip: "192.155.5.11"
        cfg.vm.provider :virtualbox do |v|
            v.name = "haproxy"
        cfg.vm.provision :shell, :path => "haproxyInstaller.sh"
        cfg.vm.provision :shell, :path => "haproxyStarter.sh"
        end
    end
end
